// @vitest-environment jsdom
import { readFileSync } from "fs";
import { resolve } from "path";

import "vitest-canvas-mock";
import { describe, it, expect } from "vitest";

import {
  ConceptualJourneyOptimizer,
  type RawProposalStep,
} from "../ai/conceptual-journey-optimizer";
import { UniversalConceptIntelligenceEngine } from "../ai/universal-engine";
import {
  createSemanticEntity,
  createSemanticRelationship,
} from "../ai/semantic-world";

describe("Cognora Universal Conceptual Journey Optimizer", () => {
  describe("1. AVL Tree Micro-Transformation Compression", () => {
    it("compresses an 18-step implementation plan into 4-6 meaningful conceptual milestones", () => {
      // 18 micro-steps generated by raw AI
      const raw18Steps: RawProposalStep[] = [
        // Phase 1: Insertion (Steps 1-4)
        {
          title: "Create node 10",
          explanation: "Allocate memory for node with value 10",
          operations: [{ type: "create_circle", id: "n10", value: 10 }],
        },
        {
          title: "Connect node 10 to parent 20",
          explanation: "Attach left child pointer from 20 to 10",
          operations: [
            {
              type: "connect",
              source: "n20",
              target: "n10",
              relationType: "left",
            },
          ],
        },
        {
          title: "Recalculate height of 10",
          explanation: "Height of newly inserted leaf is 1",
          operations: [
            { type: "update", target: "n10", properties: { height: 1 } },
          ],
        },
        {
          title: "Update height of 20",
          explanation: "Height of parent 20 increments to 2",
          operations: [
            { type: "update", target: "n20", properties: { height: 2 } },
          ],
        },
        // Phase 2: Diagnosis (Steps 5-6)
        {
          title: "Calculate balance factor of root 30",
          explanation:
            "Left subtree height is 2, right subtree is 0, balance factor is +2",
          operations: [{ type: "highlight", target: "n30", color: "warning" }],
          calculations: "BF(30) = height(left) - height(right) = 2 - 0 = +2",
        },
        {
          title: "Detect Left-Left Imbalance at node 30",
          explanation:
            "Invariant violated: |BF| > 1 indicates left-heavy imbalance",
          operations: [{ type: "highlight", target: "n30", color: "danger" }],
          insight:
            "A left-left imbalance requires a single right rotation around node 20",
        },
        // Phase 3: Mechanism Execution (Steps 7-15)
        {
          title: "Prepare Right Rotation around node 20",
          explanation:
            "Pivot node 20 will ascend to become the new root of this subtree",
          operations: [{ type: "highlight", target: "n20", color: "primary" }],
        },
        {
          title: "Disconnect right child of node 20",
          explanation: "Save temporary pointer to right subtree of 20 (T2)",
          operations: [{ type: "disconnect", source: "n20", target: "t2" }],
        },
        {
          title: "Disconnect node 20 from node 30",
          explanation: "Sever the original parent-child edge between 30 and 20",
          operations: [{ type: "disconnect", source: "n30", target: "n20" }],
        },
        {
          title: "Make node 20 the new subtree root",
          explanation:
            "Update root reference of the subtree to point to node 20",
          operations: [{ type: "update", target: "n20", role: "root" }],
        },
        {
          title: "Connect node 30 as right child of node 20",
          explanation: "Node 30 descends to become the right child of node 20",
          operations: [
            {
              type: "connect",
              source: "n20",
              target: "n30",
              relationType: "right",
            },
          ],
        },
        {
          title: "Attach orphaned subtree T2 as left child of 30",
          explanation: "Maintain binary search tree ordering property for T2",
          operations: [
            {
              type: "connect",
              source: "n30",
              target: "t2",
              relationType: "left",
            },
          ],
        },
        {
          title: "Recalculate height of node 30",
          explanation: "Node 30 now has height max(0, 0) + 1 = 1",
          operations: [
            { type: "update", target: "n30", properties: { height: 1 } },
          ],
        },
        {
          title: "Recalculate height of node 20",
          explanation: "Node 20 now has height max(1, 1) + 1 = 2",
          operations: [
            { type: "update", target: "n20", properties: { height: 2 } },
          ],
        },
        {
          title: "Execute Rotation Transformation",
          explanation: "The single right rotation restructuring is complete",
          operations: [{ type: "highlight", target: "n20", color: "success" }],
        },
        // Phase 4: Final Verification & Proof (Steps 16-18)
        {
          title: "Verify balance factor of node 30",
          explanation: "BF(30) = 0, invariant satisfied",
          operations: [
            { type: "update", target: "n30", properties: { bf: 0 } },
          ],
        },
        {
          title: "Verify balance factor of node 20",
          explanation: "BF(20) = 0, invariant satisfied",
          operations: [
            { type: "update", target: "n20", properties: { bf: 0 } },
          ],
        },
        {
          title: "Balanced AVL Tree Verified",
          explanation:
            "All node balance factors are in {-1, 0, 1}. The tree is fully balanced and invariant restored.",
          operations: [{ type: "unhighlight", target: "n20" }],
          insight:
            "Self-balancing AVL invariant guaranteed in O(log N) operations.",
        },
      ];

      const milestones = ConceptualJourneyOptimizer.optimize({
        concept: "AVL Tree Balancing",
        intent: "explain",
        targetGoal: "Restore AVL balance invariant",
        rawSteps: raw18Steps,
      });

      expect(raw18Steps.length).toBe(18);
      expect(milestones.length).toBeGreaterThanOrEqual(3);
      expect(milestones.length).toBeLessThanOrEqual(6);

      // Verify essential pedagogical stages are preserved:
      // 1. Insertion
      expect(milestones[0].conceptualRole).toBe("perturbation");
      expect(milestones[0].absorbedStepsCount).toBeGreaterThanOrEqual(2);

      // 2. Diagnosis (Imbalance detected)
      const diagnosisMilestone = milestones.find(
        (m) => m.conceptualRole === "diagnosis",
      );
      expect(diagnosisMilestone).toBeDefined();
      expect(diagnosisMilestone?.explanation).toContain("balance factor");

      // 3. Mechanism (Rotation Restructuring)
      const mechanismMilestone = milestones.find(
        (m) => m.conceptualRole === "mechanism",
      );
      expect(mechanismMilestone).toBeDefined();
      expect(mechanismMilestone?.absorbedStepsCount).toBeGreaterThanOrEqual(3);

      // 4. Proof (Balanced Tree Verified)
      const proofMilestone = milestones[milestones.length - 1];
      expect(proofMilestone.conceptualRole).toBe("proof");
      expect(proofMilestone.explanation).toContain("balanced");
    });
  });

  describe("2. TCP 3-Way Handshake Causal Completeness", () => {
    it("preserves all 3-4 causal steps without loss of protocol completeness", () => {
      const tcpSteps: RawProposalStep[] = [
        {
          title: "Client sends SYN",
          explanation: "Client initiates connection with SYN packet and ISN x",
          operations: [
            {
              type: "connect_relation",
              source: "client",
              target: "server",
              relationType: "SYN",
            },
          ],
        },
        {
          title: "Server receives SYN and sends SYN-ACK",
          explanation:
            "Server allocates buffers and responds with SYN-ACK, ACK x+1, ISN y",
          operations: [
            {
              type: "connect_relation",
              source: "server",
              target: "client",
              relationType: "SYN_ACK",
            },
          ],
        },
        {
          title: "Client sends ACK",
          explanation:
            "Client acknowledges with ACK y+1 and transitions to ESTABLISHED",
          operations: [
            {
              type: "connect_relation",
              source: "client",
              target: "server",
              relationType: "ACK",
            },
          ],
        },
        {
          title: "Bidirectional Connection Established",
          explanation:
            "Both endpoints reach ESTABLISHED state. Reliable byte stream is ready.",
          operations: [
            { type: "update", target: "server", state: "ESTABLISHED" },
            { type: "update", target: "client", state: "ESTABLISHED" },
          ],
        },
      ];

      const milestones = ConceptualJourneyOptimizer.optimize({
        concept: "TCP 3-Way Handshake",
        intent: "explain",
        targetGoal: "Establish reliable connection",
        rawSteps: tcpSteps,
      });

      // No causal steps must be removed from the 4-step protocol
      expect(milestones.length).toBe(4);
      expect(milestones[0].title).toContain("SYN");
      expect(milestones[1].title).toContain("SYN-ACK");
      expect(milestones[2].title).toContain("ACK");
      expect(milestones[3].conceptualRole).toBe("proof");
    });
  });

  describe("3. DNS Resolution Multi-Hop Preservation", () => {
    it("merges internal buffer bookkeeping while preserving multi-server causal query hops", () => {
      const dnsSteps: RawProposalStep[] = [
        // Hop 1: Client to Local Resolver (with micro bookkeeping)
        {
          title: "Client creates UDP socket",
          explanation: "Allocate temporary local port for query",
          operations: [
            { type: "update", target: "client", properties: { port: 5353 } },
          ],
        },
        {
          title: "Client queries Recursive Resolver",
          explanation:
            "Client sends DNS query for example.com to Local Resolver",
          operations: [
            {
              type: "connect",
              source: "client",
              target: "resolver",
              relationType: "query",
            },
          ],
        },
        // Hop 2: Resolver to Root
        {
          title: "Resolver queries Root Nameserver",
          explanation:
            "Root nameserver provides referral to .com TLD nameserver",
          operations: [
            {
              type: "connect",
              source: "resolver",
              target: "root_ns",
              relationType: "query",
            },
          ],
        },
        // Hop 3: Resolver to TLD
        {
          title: "Resolver queries TLD Nameserver",
          explanation:
            ".com TLD nameserver returns authoritative nameserver NS records",
          operations: [
            {
              type: "connect",
              source: "resolver",
              target: "tld_ns",
              relationType: "query",
            },
          ],
        },
        // Hop 4: Resolver to Authoritative
        {
          title: "Resolver queries Authoritative Nameserver",
          explanation:
            "Authoritative nameserver returns final A record: 93.184.216.34",
          operations: [
            {
              type: "connect",
              source: "resolver",
              target: "auth_ns",
              relationType: "query",
            },
          ],
        },
        // Hop 5: Resolution complete
        {
          title: "DNS Resolution Complete",
          explanation:
            "Resolver caches the A record and delivers IP 93.184.216.34 back to client.",
          operations: [
            {
              type: "connect",
              source: "resolver",
              target: "client",
              relationType: "resolved_ip",
            },
          ],
        },
      ];

      const milestones = ConceptualJourneyOptimizer.optimize({
        concept: "DNS Resolution",
        intent: "explain",
        targetGoal: "Resolve domain name to IP",
        rawSteps: dnsSteps,
      });

      // Socket creation bookkeeping merged into Hop 1, all other hops preserved
      expect(milestones.length).toBe(5);
      expect(milestones[0].absorbedStepsCount).toBe(2);
      expect(milestones[0].explanation).toContain("Local Resolver");
      expect(milestones[4].conceptualRole).toBe("proof");
    });
  });

  describe("4. Complex Multi-Stage Concept (Compiler Pipeline)", () => {
    it("does not artificially truncate complex 7+ stage pipeline when causality requires each stage", () => {
      const compilerStages: RawProposalStep[] = [
        {
          title: "1. Lexical Analysis",
          explanation: "Source code is converted into stream of tokens",
          operations: [{ type: "update", target: "tokens", value: "stream" }],
        },
        {
          title: "2. Syntax Analysis",
          explanation: "Tokens are parsed into Abstract Syntax Tree (AST)",
          operations: [{ type: "update", target: "ast", value: "tree" }],
        },
        {
          title: "3. Semantic Analysis",
          explanation: "Type checking and scope resolution verify invariants",
          operations: [
            { type: "update", target: "symbol_table", value: "verified" },
          ],
        },
        {
          title: "4. Intermediate Code Generation",
          explanation: "AST is lowered to linear 3-Address Code IR",
          operations: [{ type: "update", target: "ir", value: "tac" }],
        },
        {
          title: "5. Target-Independent Optimization",
          explanation: "Dead code elimination and constant folding",
          operations: [
            { type: "update", target: "opt_ir", value: "optimized" },
          ],
        },
        {
          title: "6. Register Allocation",
          explanation:
            "Variables mapped to CPU hardware registers via graph coloring",
          operations: [
            { type: "update", target: "registers", value: "allocated" },
          ],
        },
        {
          title: "7. Instruction Selection",
          explanation: "IR opcodes translated to native machine instructions",
          operations: [{ type: "update", target: "asm", value: "x86_64" }],
        },
        {
          title: "8. Machine Code Verified",
          explanation: "Binary executable generated and verified",
          operations: [{ type: "update", target: "binary", value: "elf" }],
        },
      ];

      const milestones = ConceptualJourneyOptimizer.optimize({
        concept: "Compiler Pipeline",
        intent: "explain",
        targetGoal: "Transform source code to verified machine code",
        rawSteps: compilerStages,
      });

      // Complex multi-stage pipelines retain depth (> 6 milestones)
      expect(milestones.length).toBe(8);
      expect(milestones[7].conceptualRole).toBe("proof");
    });
  });

  describe("5. Simple Concept (Queue Enqueue / Dequeue)", () => {
    it("remains concise (2-3 milestones) without creating artificial bloat", () => {
      const queueSteps: RawProposalStep[] = [
        {
          title: "Enqueue element 42",
          explanation: "Element is appended to the tail of the FIFO queue",
          operations: [{ type: "add_entity", id: "el42", value: 42 }],
        },
        {
          title: "Dequeue front element",
          explanation: "Oldest element at the head of the queue is removed",
          operations: [{ type: "delete_entity", id: "el10" }],
        },
        {
          title: "FIFO Invariant Verified",
          explanation: "First-in first-out ordering invariant satisfied",
          operations: [
            { type: "highlight", target: "queue", color: "success" },
          ],
        },
      ];

      const milestones = ConceptualJourneyOptimizer.optimize({
        concept: "Queue Operations",
        intent: "explain",
        targetGoal: "Demonstrate FIFO operations",
        rawSteps: queueSteps,
      });

      expect(milestones.length).toBe(3);
    });
  });

  describe("6. Unknown Fictional Concept", () => {
    it("derives dynamic progression without any domain-specific logic", () => {
      const fictionalSteps: RawProposalStep[] = [
        {
          title: "Device A generates flux",
          explanation: "Initial energy flux of 100 units emitted",
          operations: [
            { type: "update", target: "device_a", value: "100_flux" },
          ],
        },
        {
          title: "Device A transfers flux to Device B",
          explanation: "Flux channeled across conduit to converter B",
          operations: [
            {
              type: "connect",
              source: "device_a",
              target: "device_b",
              relationType: "channels",
            },
          ],
        },
        {
          title: "Device B transforms flux into plasma",
          explanation: "Internal transformation modifies energy state",
          operations: [
            { type: "update", target: "device_b", state: "plasma_active" },
          ],
        },
        {
          title: "Device B deposits plasma into Containment C",
          explanation: "Plasma routed to final storage matrix",
          operations: [
            {
              type: "connect",
              source: "device_b",
              target: "device_c",
              relationType: "deposits",
            },
          ],
        },
        {
          title: "Containment C Stabilized and Verified",
          explanation: "Energy stored safely. Invariant: zero leak verified.",
          operations: [
            { type: "update", target: "device_c", value: "stored_100" },
          ],
        },
      ];

      const milestones = ConceptualJourneyOptimizer.optimize({
        concept: "Flux Transmutation System",
        intent: "explain",
        targetGoal: "Channel and store energy safely",
        rawSteps: fictionalSteps,
      });

      expect(milestones.length).toBeGreaterThanOrEqual(3);
      expect(milestones.length).toBeLessThanOrEqual(5);
      expect(milestones[milestones.length - 1].conceptualRole).toBe("proof");
    });
  });

  describe("7. Zero Topic-Specific Logic Verification", () => {
    it("verifies that the optimizer contains ZERO topic keywords in its implementation", () => {
      const filePath = resolve(
        __dirname,
        "../ai/conceptual-journey-optimizer.ts",
      );
      const fileContent = readFileSync(filePath, "utf-8");

      // Topic words that must NEVER appear in the optimizer code
      const forbiddenTopicKeywords = [
        "AVL",
        "BST",
        "TCP",
        "DNS",
        "BFS",
        "DFS",
        "BinarySearch",
        "LinkedList",
        "Dijkstra",
        "Schnorr",
        "Thermodynamics",
        "Refrigerat",
      ];

      for (const keyword of forbiddenTopicKeywords) {
        const regex = new RegExp(`\\b${keyword}\\b`, "i");
        expect(fileContent).not.toMatch(regex);
      }
    });
  });

  describe("8. Full Universal Engine End-to-End Integration", () => {
    it("guarantees 1-to-1 sync across model states, visual transformations, and compiled timeline", () => {
      const result = UniversalConceptIntelligenceEngine.processQuestion(
        "Explain AVL tree insertion causing left rotation",
        {
          entities: [
            createSemanticEntity("n10", "TreeNode", "10", {}, { value: 10 }),
            createSemanticEntity("n20", "TreeNode", "20", {}, { value: 20 }),
            createSemanticEntity("n30", "TreeNode", "30", {}, { value: 30 }),
          ],
          relationships: [
            createSemanticRelationship("r1", "n30", "n20", "left"),
          ],
          steps: [
            {
              title: "Create node 10",
              explanation: "Leaf node 10 created",
              operations: [{ type: "create_circle", id: "n10", value: 10 }],
            },
            {
              title: "Connect node 10 to parent 20",
              explanation: "Attached as left child of 20",
              operations: [{ type: "connect", source: "n20", target: "n10" }],
            },
            {
              title: "Recalculate height",
              explanation: "Height of 20 becomes 2",
              operations: [
                { type: "update", target: "n20", properties: { height: 2 } },
              ],
            },
            {
              title: "Detect Imbalance at node 30",
              explanation:
                "Balance factor of 30 is +2, violating AVL invariant",
              operations: [
                { type: "highlight", target: "n30", color: "danger" },
              ],
            },
            {
              title: "Execute Right Rotation",
              explanation:
                "Node 20 ascends to become root; node 30 becomes right child of 20",
              operations: [
                { type: "disconnect", source: "n30", target: "n20" },
                { type: "connect", source: "n20", target: "n30" },
              ],
            },
            {
              title: "Tree Balanced and Verified",
              explanation:
                "All balance factors in {-1, 0, 1}. AVL tree invariant restored.",
              operations: [{ type: "unhighlight", target: "n30" }],
            },
          ],
        },
      );

      // Model transformations count must match visual lesson transformations count
      expect(result.authoritativeModel.transformations.length).toBe(
        result.visualLesson.transformations.length,
      );

      // Compiled timeline must have exactly 1 initial state + 1 state per transformation
      expect(result.timeline.states.length).toBe(
        result.authoritativeModel.transformations.length + 1,
      );

      // Meta count matches states count
      expect(result.timeline.meta.length).toBe(result.timeline.states.length);

      // Goal satisfied
      expect(result.authoritativeModel.goalSatisfaction.satisfied).toBe(true);
    });
  });
});
