import { describe, it, expect, vi, beforeEach } from "vitest";

import { ProviderRouter } from "../ai/backend/provider-router";
import {
  ProviderRateLimitError,
  ProviderCreditCapacityError,
  ProviderTimeoutError,
  ProviderNetworkError,
  ProviderSchemaError,
  ProviderAuthenticationError,
} from "../ai/backend/provider-errors";
import { isRecoverableProviderError } from "../ai/backend/ai-provider";

import type { AIProvider } from "../ai/backend/ai-provider";
import type {
  TeachingRequest,
  TeachingResponse,
} from "../ai/teaching-contract";

const PRIMARY_MOCK_RESPONSE: TeachingResponse = {
  topic: "Primary Topic",
  message: "Generated by primary provider",
  explanation_steps: ["Point 1", "Point 2"],
  visual_actions: [
    {
      type: "create_box",
      id: "box-1",
      label: "Primary Box",
    },
  ],
};

const FALLBACK_MOCK_RESPONSE: TeachingResponse = {
  topic: "Fallback Topic",
  message: "Generated by fallback provider",
  explanation_steps: ["Fallback Point 1"],
  visual_actions: [
    {
      type: "create_box",
      id: "box-fallback",
      label: "Fallback Box",
    },
  ],
};

describe("ProviderRouter", () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });

  describe("isRecoverableProviderError helper", () => {
    it("recognizes operational errors as recoverable", () => {
      expect(
        isRecoverableProviderError(
          new ProviderRateLimitError("Rate limited", "nvidia"),
        ),
      ).toBe(true);
      expect(
        isRecoverableProviderError(
          new ProviderCreditCapacityError(
            "insufficient credits",
            { limitSource: "nvidia" },
            "nvidia",
          ),
        ),
      ).toBe(true);
      expect(
        isRecoverableProviderError(new ProviderTimeoutError(35000, "nvidia")),
      ).toBe(true);
      expect(
        isRecoverableProviderError(
          new ProviderNetworkError("connect ECONNREFUSED", "nvidia"),
        ),
      ).toBe(true);
    });

    it("rejects schema and contract errors as non-recoverable", () => {
      expect(
        isRecoverableProviderError(
          new ProviderSchemaError(
            "invalid JSON schema",
            ["schema failure"],
            "nvidia",
          ),
        ),
      ).toBe(false);
      expect(
        isRecoverableProviderError(
          new ProviderAuthenticationError("Bad token", "nvidia"),
        ),
      ).toBe(false);
      expect(
        isRecoverableProviderError(new Error("SyntaxError in app code")),
      ).toBe(false);
    });
  });

  describe("Single Dispatch Workflow", () => {
    it("fails directly when primary encounters ProviderRateLimitError", async () => {
      const { ProviderRouter } = await import("../ai/backend/provider-router");
      const primaryMock = {
        id: "mock-primary",
        name: "Mock Primary",
        isConfigured: () => true,
        generateTeachingLesson: vi
          .fn()
          .mockRejectedValue(
            new ProviderRateLimitError("Rate limited", "nvidia"),
          ),
      };

      const router = new ProviderRouter({ primaryProvider: primaryMock });
      const req = { prompt: "test rate limit", lessonType: "conceptual" };

      await expect(router.generateTeachingLesson(req)).rejects.toThrow(
        ProviderRateLimitError,
      );
    });

    it("fails directly when primary encounters ProviderCreditCapacityError", async () => {
      const { ProviderRouter } = await import("../ai/backend/provider-router");
      const primaryMock = {
        id: "mock-primary",
        name: "Mock Primary",
        isConfigured: () => true,
        generateTeachingLesson: vi
          .fn()
          .mockRejectedValue(
            new ProviderCreditCapacityError(
              "Credit limit reached",
              undefined,
              "nvidia",
            ),
          ),
      };
      const router = new ProviderRouter({ primaryProvider: primaryMock });
      const req = { prompt: "test capacity", lessonType: "conceptual" };

      await expect(router.generateTeachingLesson(req)).rejects.toThrow(
        ProviderCreditCapacityError,
      );
    });
  });
});
