/**
 * Universal Text Sanitization & Semantic Detail Compression — Cognora 5.0
 *
 * Cleanses raw text strings from serialization artifacts, escaped HTML,
 * unformatted JSON, debug IDs, and newline explosions before rendering to canvas.
 * Preserves math notation, code, SQL, scientific formulas, and valid protocol terms.
 */

export interface CompressedPayload {
  title: string;
  subtitle?: string;
  fullDetail: string;
}

/**
 * Universal visual text sanitizer.
 */
export function sanitizeVisualText(raw: unknown): string {
  if (raw === null || raw === undefined) return "";
  let str = String(raw).trim();
  if (!str) return "";

  // 1. Unescape common HTML entities
  str = str
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&amp;/g, "&")
    .replace(/&nbsp;/g, " ");

  // 2. Remove accidental internal debug prefixes or machine UUIDs (e.g. "entity-1738294719283-")
  // Only remove if it looks like an autogenerated ID at the start of the string
  str = str.replace(/^(?:entity|node|rel|edge|state|item|step)_[a-zA-Z0-9]{8,}(?:_|\s*:\s*)/i, "");
  str = str.replace(/^temp_[a-zA-Z0-9_\-]+(?:\s*:\s*)/i, "");

  // 3. Remove raw serialization tags like "[object Object]"
  if (str.includes("[object Object]")) {
    str = str.replace(/\[object Object\]/g, "").trim();
  }

  // 4. Remove accidental JSON wrapper noise if the entire string is wrapped in { "..." } or similar
  if (str.startsWith('{"') && str.endsWith('}')) {
    try {
      const parsed = JSON.parse(str);
      if (typeof parsed === "object" && parsed !== null) {
        // Extract common pedagogical summary fields if present
        const summary = parsed.summary || parsed.label || parsed.name || parsed.value || parsed.message;
        if (typeof summary === "string") {
          str = summary;
        }
      }
    } catch {
      // not valid JSON, proceed
    }
  }

  // 5. Clean up redundant consecutive newlines (newline explosions)
  str = str.replace(/\r\n/g, "\n").replace(/\n{3,}/g, "\n\n");

  // 6. Clean up control characters except \n and \t
  str = str.replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, "");

  return str.trim();
}

/**
 * Compresses lengthy textual payloads for readable canvas rendering.
 * Retains full details for the Inspector / Explanation panel.
 */
export function compressSemanticPayload(
  payload: unknown,
  maxDisplayLength = 32,
): CompressedPayload {
  const fullDetail = sanitizeVisualText(payload);
  if (!fullDetail) {
    return { title: "", fullDetail: "" };
  }

  // If already compact, keep as-is
  if (fullDetail.length <= maxDisplayLength && !fullDetail.includes("\n")) {
    return {
      title: fullDetail,
      fullDetail,
    };
  }

  // First line or natural sentence boundary
  const lines = fullDetail.split("\n").map((l) => l.trim()).filter(Boolean);
  const firstLine = lines[0] || fullDetail;

  // Domain-agnostic protocol/header detection:
  // E.g. "HTTP/1.1 200 OK Content-Type: text/html..." -> "HTTP 200 OK" / "HTML response"
  if (/^HTTP\/[0-9.]+\s+[0-9]{3}/i.test(firstLine)) {
    const statusMatch = firstLine.match(/^(?:HTTP\/[0-9.]+\s+)?([0-9]{3}\s+[A-Za-z\s]+)/i);
    const title = statusMatch ? `HTTP ${statusMatch[1].trim()}` : firstLine.slice(0, maxDisplayLength);
    const hasHtml = fullDetail.toLowerCase().includes("html");
    const hasJson = fullDetail.toLowerCase().includes("json");
    const subtitle = hasJson ? "JSON response" : hasHtml ? "HTML document" : undefined;
    return { title, subtitle, fullDetail };
  }

  // E.g. TCP SYN / ACK flags with sequence numbers: "SYN, seq=100, ack=0, win=65535" -> "SYN (seq=100)"
  if (/^(?:SYN|ACK|FIN|RST|PSH|URG)/i.test(firstLine)) {
    const parts = firstLine.split(/[,;\s]+/).filter(Boolean);
    const title = parts.slice(0, 2).join(" ");
    const subtitle = parts.length > 2 ? parts.slice(2, 4).join(" ") : undefined;
    return { title, subtitle, fullDetail };
  }

  // E.g. SQL query or statements: "SELECT users.id, users.name, orders.total FROM users JOIN orders ON..." -> "SELECT users JOIN orders"
  if (/^(?:SELECT|INSERT|UPDATE|DELETE|CREATE|DROP)\s+/i.test(firstLine)) {
    if (firstLine.length > maxDisplayLength) {
      const summary = firstLine.slice(0, maxDisplayLength).trim() + "...";
      return { title: summary, fullDetail };
    }
    return { title: firstLine, fullDetail };
  }

  // General text truncation with ellipsis
  if (firstLine.length > maxDisplayLength) {
    const title = firstLine.slice(0, maxDisplayLength - 3).trim() + "...";
    return {
      title,
      subtitle: lines.length > 1 ? lines[1].slice(0, maxDisplayLength) : undefined,
      fullDetail,
    };
  }

  return {
    title: firstLine,
    subtitle: lines.length > 1 ? lines[1].slice(0, maxDisplayLength) : undefined,
    fullDetail,
  };
}
